# Generated by Django 4.2.4 on 2023-09-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/file')),
                ('category', models.CharField(choices=[('animation', 'Animation'), ('podcast', 'Podcast')], max_length=10)),
                ('banner', models.FileField(upload_to='videos/banner')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
