# Generated by Django 4.2.5 on 2023-10-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kidtv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(
                choices=[
                    ("animation", "Animation"),
                    ("podcast", "Podcast"),
                    ("number", "Number"),
                    ("myfamiy", "Myfamily"),
                    ("alphabetic", "Alphabetic"),
                    ("myhome", "Myhome"),
                ],
                max_length=10,
            ),
        ),
    ]
